name: Deploy Go Application

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'  # Specify the Go version

      - name: Build Go application
        run: go build -o trackPixel main.go

      - name: Package application
        run: zip -r trackPixel.zip trackPixel transparent.gif Procfile

      - name: Deploy to AWS Elastic Beanstalk
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        run: |
          # Create application version
          aws elasticbeanstalk create-application-version \
            --application-name email-track \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=your-bucket-name,S3Key=trackPixel.zip

          # Update the environment to use the new version
          aws elasticbeanstalk update-environment \
            --environment-name your-environment-name \
            --version-label ${{ github.sha }}
