services:
  - type: web
    name: Go Tracking App
    env: go
    plan: free
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: GO_ENV
        value: production
    autoDeploy: true
