name: Deploy Node.js app to AWS EC2 - MarketMe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Check out the code from the repository

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Copy files via SCP
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > aws_private_key
          chmod 600 aws_private_key
          # Update the IP and username for the AWS instance
          scp -i aws_private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./* ec2-user@"${{ secrets.AWS_IP }}":/home/ec2-user/
          rm aws_private_key  # Clean up the private key file

      - name: Debugging Environment Variables
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }} is set"
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }} is set"
          echo "NAME=${{ secrets.NAME }} is set"
          echo "PORT=${{ secrets.PORT }} is set"
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} is set"

      - name: SSH to AWS EC2 and run the application
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > aws_private_key
          chmod 600 aws_private_key
          ssh -i aws_private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@"${{ secrets.AWS_IP }}"" << EOF
            # Export environment variables for the session
            export JWT_SECRET="${{ secrets.JWT_SECRET }}"
            export MONGODB_URI="${{ secrets.MONGODB_URI }}"
            export NAME="${{ secrets.NAME }}"
            export PORT="${{ secrets.PORT }}"
            export REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}"

            cd /home/ec2-user

            # Debugging: Print the variables to ensure they are set
            echo "JWT_SECRET=\$JWT_SECRET"
            echo "MONGODB_URI=\$MONGODB_URI"
            echo "NAME=\$NAME"
            echo "PORT=\$PORT"
            echo "REDIS_PASSWORD=\$REDIS_PASSWORD"

            # Install npm packages if necessary
            npm install --production --omit=dev

            # Start or restart the app using PM2
            pm2 start ecosystem.config.js --env production || pm2 restart marketme
          EOF
          rm aws_private_key  # Clean up the private key file

      - name: Notify Deployment
        run: |
          echo "Deployed to AWS EC2 instance"
          echo "Deployment completed at $(date)"
