name: Build and deploy Node.js app to Azure VM - marketme

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install
        run: npm install

      - name: Archive production artifacts
        run: |
          mkdir -p ./dist
          shopt -s extglob  # Enable extended globbing
          cp -r !("dist") ./dist  # Copy everything except the "dist" directory
          cd ./dist
          zip -r ../dist.zip .  # Zip the contents of the dist directory

      - name: List files after zipping
        run: |
          echo "Listing files in the dist directory:"
          ls -la dist
          echo "Files in the current directory:"
          ls -la .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: List files in the current directory before copying
        run: |
          echo "Files in the current directory:"
          ls -la

      - name: Copy files via SCP
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./dist.zip azureuser@40.78.122.33:/home/azureuser/

      - name: SSH to VM and deploy
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null azureuser@40.78.122.33 << 'EOF'
            # Unzip the application files
            unzip -o /home/azureuser/dist.zip -d /home/azureuser/
            cd /home/azureuser
            
            # Install npm packages and start the application
            npm install --production
            
            # Restart the application using PM2
            pm2 start index.js --name marketme || pm2 restart marketme
          EOF

      - name: Notify Deployment
        run: |
          echo "Deployed to Azure VM"
          echo "Deployment completed at $(date)"
