name: Build and deploy Node.js app to Azure Web App - marketme

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install and build
        run: |
          npm i
       

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_48D1D965DFE4412E903BCE9C7FA93E7D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_74FEED099BFE44B5ACF17262541A58AB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_122EF020D13D4B439BB9081F653E9156 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'marketme'
          slot-name: 'production'
          package: .
          # Adding app settings if needed
         

      - name: Notify Deployment
        run: |
          echo "Deployed to ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
          echo "Deployment completed at $(date)"
      
      - name: Check for running app
        run: |
          echo "Checking app status..."
          curl -f ${{ steps.deploy-to-webapp.outputs.webapp-url }} || echo "App is not responding."

      - name: Enable logging
        run: |
          echo "Enabling logging for better troubleshooting..."
          az webapp log config --name marketme --resource-group <YourResourceGroup> --application-logging true --detailed-error-messages true --failed-request-tracing true
