name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: /home/ubuntu/actions-runner-backend/_work/test/test

    - name: Ensure PM2 is installed
      run: npm install -g pm2
      working-directory: /home/ubuntu/actions-runner-backend/_work/test/test

    - name: Start or Restart Application with PM2
      run: |
        pm2 start ecosystem.config.js --env development || pm2 restart ecosystem.config.js --env development
        pm2 save
        pm2 list
      env:
        PM2_HOME: ~/.pm2
        name: ${{ secrets.NAME }}  # This pulls 'name' from GitHub Secrets
      working-directory: /home/ubuntu/actions-runner-backend/_work/test/test

    - name: Display PM2 logs
      run: pm2 logs --lines 100
      working-directory: /home/ubuntu/actions-runner-backend/_work/test/test
