name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: ${{ github.workspace }}

    - name: Ensure PM2 is installed
      run: npm install -g pm2
      working-directory: ${{ github.workspace }}

    - name: Start Application with PM2
      run: |
        if pm2 list | grep -q 'index'; then
          echo "Application is already running. Restarting..."
          pm2 restart ecosystem.config.js --env development
        else
          echo "Application is not running. Starting..."
          pm2 start ecosystem.config.js --env development
        fi
        pm2 save
        pm2 list
      working-directory: ${{ github.workspace }}

    - name: Display PM2 logs
      run: pm2 logs --lines 100
      working-directory: ${{ github.workspace }}
