name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 3 # Set the timeout for the job
    strategy:
      matrix:
        node-version: [18]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: /home/ubuntu/actions-runner-backend/_work/test/test

    - name: Ensure PM2 is installed
      run: npm install -g pm2
      working-directory: /home/ubuntu/actions-runner-backend/_work/test/test

    - name: Print environment variables
      run: printenv
      working-directory: /home/ubuntu/actions-runner-backend/_work/test/test

    - name: Start or Restart Application with PM2
      run: |
          # Ensure PM2 is using the correct home directory
          export PM2_HOME=~/.pm2

          # Delete any existing 'index' process, ignore errors if it doesn't exist
          pm2 delete index || true

          # Start or restart the Node.js application with PM2
          pm2 start index.js --name index --watch --env development

          # Save the PM2 process list and force update
          pm2 save -f

          # Display the list of processes managed by PM2
          pm2 list
      env:
        PM2_HOME: ~/.pm2
        NODE_ENV: development
        NAME: ${{ secrets.NAME }}  # Add 'name' from GitHub Secrets
      working-directory: /home/ubuntu/actions-runner-backend/_work/test/test

    - name: Display PM2 logs
      run: |
        pm2 logs --lines 100
      working-directory: /home/ubuntu/actions-runner-backend/_work/test/test
