# This workflow will install dependencies, deploy to EC2, and run the app with PM2.

name: Node.js CI and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Step 1: Check out the repository code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js with caching for npm packages
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Set environment variables for the build
      - name: Set Environment Variables
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NAME: ${{ secrets.NAME }}
          PORT: ${{ secrets.PORT }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: |
          touch .env
          echo "JWT_SECRET=$JWT_SECRET" >>.env
          echo "MONGODB_URI=$MONGODB_URI" >>.env
          echo "NAME=$NAME" >>.env
          echo "PORT=$PORT" >>.env
          echo "PRIVATE_KEY=$PRIVATE_KEY" >>.env
          echo "REDIS_PASSWORD=$REDIS_PASSWORD" >>.env
          echo "Environment variables set for the job"

      # Step 5: Install PM2 globally
      - name: Install PM2
        run: sudo npm install -g pm2
      
      - name: Restart server
        run: pm2 restart index
    