name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: /home/ubuntu/actions-runner-backend/_work/test/test

    - name: Deploy and Start Application
      run: |
        # Change to the deployment directory
        cd /home/ubuntu/actions-runner-backend/_work/test/test

        # Stop any existing PM2 process if it exists
      

        # Start the new application
        pm2 stop chal
        pm2 start chal
        
      env:
        PM2_HOME: ~/.pm2
