# This workflow will install dependencies, deploy to EC2, and run the app with PM2.

name: Node.js CI and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Step 1: Check out the repository code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js with caching for npm packages
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Set environment variables for the build
      - name: Set Environment Variables
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NAME: ${{ secrets.NAME }}
          PORT: ${{ secrets.PORT }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: |
          echo "Environment variables set for the job"

      # Step 5: Install PM2 globally
      - name: Install PM2
        run: sudo npm install -g pm2

      # Step 6: Deploy code to AWS EC2 instance
      - name: Deploy to AWS EC2
        env:
          AWS_HOST: ${{ secrets.AWS_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER: ubuntu
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H $AWS_HOST >> ~/.ssh/known_hosts
          scp -i key.pem -o StrictHostKeyChecking=no -r ./* $USER@$AWS_HOST:/home/ubuntu/app

      # Step 7: SSH into EC2 and run the app with PM2
      - name: Start application with PM2 on EC2
        env:
          AWS_HOST: ${{ secrets.AWS_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER: ubuntu
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $USER@$AWS_HOST << EOF
            cd /home/ubuntu/app
            npm install
            pm2 start index.js --name "my-app"
            pm2 save
          EOF

      # Step 8: Optional - Check PM2 status on EC2
      - name: PM2 Status on EC2
        env:
          AWS_HOST: ${{ secrets.AWS_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER: ubuntu
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $USER@$AWS_HOST "pm2 status"
